-- 1. Races Table
CREATE TABLE IF NOT EXISTS public.races (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_date DATE NOT NULL,
    place_code TEXT NOT NULL,
    place_name TEXT NOT NULL,
    race_number INT NOT NULL,
    race_title TEXT,
    weather TEXT,
    wind_direction TEXT,
    wind_speed FLOAT8,
    wave_height FLOAT8,
    is_exhibition_done BOOLEAN DEFAULT FALSE,
    scheduled_time TEXT,
    is_finished BOOLEAN DEFAULT FALSE,
    ranking_str TEXT,
    ai_predictions_json JSONB,
    result_json JSONB,
    odds_json JSONB,
    day_label TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(race_date, place_code, race_number)
);

-- 2. Entries Table
CREATE TABLE IF NOT EXISTS public.entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_date DATE NOT NULL,
    place_code TEXT NOT NULL,
    race_number INT NOT NULL,
    boat_number INT NOT NULL,
    racer_name TEXT,
    racer_class TEXT,
    racer_id TEXT,
    global_win_rate FLOAT8,
    global_2_quinella FLOAT8,
    local_win_rate FLOAT8,
    local_2_quinella FLOAT8,
    motor_number INT,
    motor_2_quinella FLOAT8,
    boat_number_machine INT,
    boat_2_quinella FLOAT8,
    exhibition_time FLOAT8,
    start_timing FLOAT8,
    entry_course INT,
    arrival_order INT,
    race_time TEXT,
    tilt FLOAT8,
    is_absent BOOLEAN DEFAULT FALSE,
    parts_exchange TEXT,
    weight_adjustment FLOAT8,
    pre_inspection_time FLOAT8,
    propeller TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(race_date, place_code, race_number, boat_number)
);

-- 3. Racer Profiles & Results
CREATE TABLE IF NOT EXISTS public.racer_profiles (
    toban TEXT PRIMARY KEY,
    name TEXT,
    course_stats JSONB,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.racer_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    racer_id TEXT NOT NULL,
    place_code TEXT,
    place_name TEXT,
    race_date DATE,
    race_no INT,
    course INT,
    start_timing FLOAT8,
    rank INT,
    race_title TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(racer_id, place_code, race_date, race_no)
);

-- 4. User Data (Favorites & Profiles)
CREATE TABLE IF NOT EXISTS public.favorite_racers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    toban TEXT NOT NULL,
    name TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(toban, user_id)
);

CREATE TABLE IF NOT EXISTS public.cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    race_id BIGINT NOT NULL,
    cart_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, race_id)
);

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    subscription_status TEXT DEFAULT 'trial', -- 'free', 'trial', 'premium'
    trial_ends_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '3 days'),
    subscription_ends_at TIMESTAMPTZ,
    payment_name TEXT,
    payment_method TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Automating Profile Creation on Signup
-- Create a function to handle new user profiles
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (
    new.id, 
    COALESCE(new.email, new.raw_user_meta_data->>'email')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create the trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 6. Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_races_date ON public.races(race_date);
CREATE INDEX IF NOT EXISTS idx_entries_race_key ON public.entries(race_date, place_code, race_number);
CREATE INDEX IF NOT EXISTS idx_racer_results_racer_id ON public.racer_results(racer_id);
CREATE INDEX IF NOT EXISTS idx_favorite_racers_user_id ON public.favorite_racers(user_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_user_id ON public.cart_items(user_id);

-- 7. Row Level Security (RLS) Policies
ALTER TABLE public.favorite_racers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

-- Policies for favorite_racers
CREATE POLICY "Users can view their own favorites" ON public.favorite_racers FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own favorites" ON public.favorite_racers FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own favorites" ON public.favorite_racers FOR DELETE USING (auth.uid() = user_id);

-- Policies for cart_items
CREATE POLICY "Users can view their own cart items" ON public.cart_items FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own cart items" ON public.cart_items FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own cart items" ON public.cart_items FOR DELETE USING (auth.uid() = user_id);
